### ISSUE TITLE
Statistics and Machine Learning in Python does not have a link

### ISSUE THREAD

**Issue by AdiBro** [JamesLavin/my_tech_resources#1]
Statistics and Machine Learning in Python - Edouard Duchesnay, Tommy Löfstedt 
Here is an optional link - ftp://ftp.cea.fr/pub/unati/people/educhesnay/pystatml/StatisticsMachineLearningPythonDraft.pdf

**Comment by JamesLavin** [comment]
Thank you, @AdiBro, for bringing this to my attention.

Interestingly, that exact link is already in my source Markdown document, but it's not rendering as a link. I'm guessing that's due to it being an "ftp://" resource. Hmmm....

**Comment by JamesLavin** [comment]
@AdiBro This appears to be a Github bug that has been around since at least 2013! #sigh

https://github.com/gollum/gollum/issues/759

**Comment by AdiBro** [comment]
I see, @JamesLavin! In that case, I have a suggestion for you - you can use a url shortening service (like SnipURL or TinyURL), and then you get an HTTPS address that renders properly on GitHub. I checked to make sure it works 🙂 I hope that helps!
Also, thank you so much for this great list of resources - I found it very useful! 👍

**Comment by JamesLavin** [comment]
Thanks for the great suggestion, @AdiBro! I've just done exactly that and tested that it now works properly. :+1: 

Really appreciate you taking time to reach out to help fix the link and thank me!

Please feel free to send along any useful resources you find, and I'll add them to make this as useful as possible for everyone.

Cheers,

James

**Comment by JamesLavin** [comment]
Good point, @bf4. Thanks. Closing!

**Comment by AdiBro** [comment]
You're very welcome, @JamesLavin! 
Sounds good - will do! I actually created a repo dedicated to data science and machine learning resources, feel free to check it out - https://github.com/AdiBro/Data-Science-Resources

**Comment by JamesLavin** [comment]
I've just added your site under "Statistical Analysis," @AdiBro. Thanks for letting me know about it! It will show up next time I push an update from my personal laptop.
